/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_asyncparseriterator_free: (a: number, b: number) => void;
export const __wbg_parseriterator_free: (a: number, b: number) => void;
export const __wbg_parseriteratorresult_free: (a: number, b: number) => void;
export const __wbg_querysolutions_free: (a: number, b: number) => void;
export const __wbg_querytriples_free: (a: number, b: number) => void;
export const __wbg_store_free: (a: number, b: number) => void;
export const asyncparseriterator_Symbol_asyncIterator: (a: number) => number;
export const asyncparseriterator_next: (a: number) => any;
export const main: () => void;
export const parse: (a: any, b: any) => [number, number, number];
export const parseriterator_Symbol_iterator: (a: number) => number;
export const parseriterator_next: (a: number) => [number, number, number];
export const parseriteratorresult_done: (a: number) => number;
export const parseriteratorresult_value: (a: number) => any;
export const querysolutions_nextBatch: (a: number, b: number) => [number, number, number];
export const querysolutions_variables: (a: number) => any;
export const querytriples_nextBatch: (a: number, b: number) => [number, number, number];
export const store_add: (a: number, b: any) => [number, number];
export const store_delete: (a: number, b: any) => [number, number];
export const store_dump: (a: number, b: any) => [number, number, number, number];
export const store_has: (a: number, b: any) => [number, number, number];
export const store_load: (a: number, b: any, c: any) => [number, number];
export const store_match: (a: number, b: any, c: any, d: any, e: any) => [number, number, number, number];
export const store_new: (a: any) => [number, number, number];
export const store_query: (a: number, b: number, c: number, d: any) => [number, number, number];
export const store_querySolutions: (a: number, b: number, c: number, d: any) => [number, number, number];
export const store_queryTriples: (a: number, b: number, c: number, d: any) => [number, number, number];
export const store_size: (a: number) => [number, number, number];
export const store_update: (a: number, b: number, c: number, d: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h64e802d339b4498d: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h462f8c2ae7c79c79: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
